### ISSUE TITLE
cannot build on hyprland 0.52.2

### ISSUE THREAD

**Issue by Postboote1** [KZDKM/Hyprspace#213]
Cannot build hyprspace on hyprland 0.52.2 on Nixos.
```bash 
error: Cannot build '/nix/store/k75hzjb4sb631z9ymbkpsxwgv26iv2l8-Hyprspace-0.1+date=2025-12-04_0467be8.drv'.
       Reason: builder failed with exit code 2.
       Output paths:
         /nix/store/a9c0nfvl1frkgqdr93sw1aii165rk4il-Hyprspace-0.1+date=2025-12-04_0467be8
       Last 25 log lines:
       > src/Render.cpp: In member function 'void CHyprspaceWidget::draw()':
       > src/Render.cpp:189:248: warning: narrowing conversion of 'Config::panelBorderWidth' from 'int' to 'double' [-Wnarrowing]
       >   189 |         CBox borderBox = {widgetBox.x, owner->m_position.y + (Config::onBottom * owner->m_transformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset->value() * owner->m_scale) * bottomInvert, owner->m_transformedSize.x, Config::panelBorderWidth};
       >       |                                                                                                                                                                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~~
       > src/main.cpp: In function 'void onRender(void*, SCallbackInfo&, std::any)':
       > src/main.cpp:145:36: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
       >   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
       >       |                                    ^~~~~~~~~~~~
       > src/main.cpp:145:92: error: 'eOverridePriority' has not been declared
       >   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
       >       |                                                                                            ^~~~~~~~~~~~~~~~~
       > src/main.cpp:145:58: error: 'CWindowOverridableVar' was not declared in this scope
       >   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
       >       |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
       > src/main.cpp:149:36: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
       >   149 |                         curWindow->m_windowData.noBlur.unset(eOverridePriority::PRIORITY_SET_PROP);
       >       |                                    ^~~~~~~~~~~~
       > src/main.cpp:149:62: error: 'eOverridePriority' has not been declared
       >   149 |                         curWindow->m_windowData.noBlur.unset(eOverridePriority::PRIORITY_SET_PROP);
       >       |                                                              ^~~~~~~~~~~~~~~~~
       > src/main.cpp: In function 'void onTouchDown(void*, SCallbackInfo&, std::any)':
       > src/main.cpp:291:68: error: 'class CCompositor' has no member named 'm_lastMonitor'
       >   291 |     targetMonitor = targetMonitor ? targetMonitor : g_pCompositor->m_lastMonitor.lock();
       >       |                                                                    ^~~~~~~~~~~~~
       > make: *** [Makefile:9: all] Error 1
       For full logs, run:
         nix log /nix/store/k75hzjb4sb631z9ymbkpsxwgv26iv2l8-Hyprspace-0.1+date=2025-12-04_0467be8.drv
```

Full logs from hyprspace build:
```bash
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/lplz5ki57q5f0x2fph8nvmm9llj5v64q-1z2w2n5qnm1nq150xr3l4knlimwjv1y0-source
source root is 1z2w2n5qnm1nq150xr3l4knlimwjv1y0-source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: SHELL=/nix/store/rlq03x4cwf8zn73hxaxnx0zn5q9kifls-bash-5.3p3/bin/bash
g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++2b -O2 `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` src/Input.cpp src/Layout.cpp src/Overview.cpp src/Render.cpp src/main.cpp -o Hyprspace.so
src/Layout.cpp: In member function 'void CHyprspaceWidget::updateLayout()':
src/Layout.cpp:38:23: error: 'class CMonitor' has no member named 'm_reservedTopLeft'; did you mean 'm_reservedArea'?
   38 |             pMonitor->m_reservedTopLeft.y = currentHeight;
      |                       ^~~~~~~~~~~~~~~~~
      |                       m_reservedArea
src/Layout.cpp:40:23: error: 'class CMonitor' has no member named 'm_reservedBottomRight'
   40 |             pMonitor->m_reservedBottomRight.y = currentHeight;
      |                       ^~~~~~~~~~~~~~~~~~~~~
src/Overview.cpp: In member function 'void CHyprspaceWidget::show()':
src/Overview.cpp:44:64: error: 'SFullscreenState' was not declared in this scope; did you mean Desktop::View::SFullscreenState'?
   44 |                     g_pCompositor->setWindowFullscreenState(w, SFullscreenState{.internal = FSMODE_NONE, .client = FSMODE_NONE});
      |                                                                ^~~~~~~~~~~~~~~~
      |                                                                Desktop::View::SFullscreenState
In file included from /nix/store/6fz8hr6nvnmxj5nc2b73wdcmk3lqbk3b-hyprland-0.52.0+date=2025-12-13_09e195d-dev/include/hyprland/src/Compositor.hpp:10,
                 from src/Overview.hpp:2,
                 from src/Overview.cpp:1:
/nix/store/6fz8hr6nvnmxj5nc2b73wdcmk3lqbk3b-hyprland-0.52.0+date=2025-12-13_09e195d-dev/include/hyprland/src/desktop/view/Window.hpp:69:12: note: 'Desktop::View::SFullscreenState' declared here
   69 |     struct SFullscreenState {
      |            ^~~~~~~~~~~~~~~~
src/Overview.cpp: In member function 'void CHyprspaceWidget::hide()':
src/Overview.cpp:111:52: error: 'SFullscreenState' was not declared in this scope; did you mean 'Desktop::View::SFullscreenState'?
  111 |         g_pCompositor->setWindowFullscreenState(w, SFullscreenState(oFullscreenMode));
      |                                                    ^~~~~~~~~~~~~~~~
      |                                                    Desktop::View::SFullscreenState
/nix/store/6fz8hr6nvnmxj5nc2b73wdcmk3lqbk3b-hyprland-0.52.0+date=2025-12-13_09e195d-dev/include/hyprland/src/desktop/view/Window.hpp:69:12: note: 'Desktop::View::SFullscreenState' declared here
   69 |     struct SFullscreenState {
      |            ^~~~~~~~~~~~~~~~
src/Render.cpp: In function 'void renderWindowStub(PHLWINDOW, PHLMONITOR, PHLWORKSPACE, Hyprutils::Math::CBox, timespec*)':
src/Render.cpp:76:47: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
   76 |     const auto oUseNearestNeighbor = pWindow->m_windowData.nearestNeighbor;
      |                                               ^~~~~~~~~~~~
src/Render.cpp:90:34: error: 'SFullscreenState' was not declared in this scope; did you mean 'Desktop::View::SFullscreenState'?
   90 |     pWindow->m_fullscreenState = SFullscreenState{FSMODE_NONE};
      |                                  ^~~~~~~~~~~~~~~~
      |                                  Desktop::View::SFullscreenState
In file included from /nix/store/6fz8hr6nvnmxj5nc2b73wdcmk3lqbk3b-hyprland-0.52.0+date=2025-12-13_09e195d-dev/include/hyprland/src/Compositor.hpp:10,
                 from src/Overview.hpp:2,
                 from src/Render.cpp:1:
/nix/store/6fz8hr6nvnmxj5nc2b73wdcmk3lqbk3b-hyprland-0.52.0+date=2025-12-13_09e195d-dev/include/hyprland/src/desktop/view/Window.hpp:69:12: note: 'Desktop::View::SFullscreenState' declared here
   69 |     struct SFullscreenState {
      |            ^~~~~~~~~~~~~~~~
src/Render.cpp:91:14: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
   91 |     pWindow->m_windowData.nearestNeighbor = false;
      |              ^~~~~~~~~~~~
src/Render.cpp:94:14: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
   94 |     pWindow->m_windowData.rounding = CWindowOverridableVar<Hyprlang::INT>(pWindow->rounding() * curScaling * pMonitor->m_scale, eOverridePriority::PRIORITY_SET_PROP);
      |              ^~~~~~~~~~~~
src/Render.cpp:94:129: error: 'eOverridePriority' has not been declared
   94 |     pWindow->m_windowData.rounding = CWindowOverridableVar<Hyprlang::INT>(pWindow->rounding() * curScaling * pMonitor->m_scale, eOverridePriority::PRIORITY_SET_PROP);
      |                                                                                                                                 ^~~~~~~~~~~~~~~~~
src/Render.cpp:94:38: error: 'CWindowOverridableVar' was not declared in this scope
   94 |     pWindow->m_windowData.rounding = CWindowOverridableVar<Hyprlang::INT>(pWindow->rounding() * curScaling * pMonitor->m_scale, eOverridePriority::PRIORITY_SET_PROP);
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/Render.cpp:111:14: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
  111 |     pWindow->m_windowData.nearestNeighbor = oUseNearestNeighbor;
      |              ^~~~~~~~~~~~
src/Render.cpp:114:14: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
  114 |     pWindow->m_windowData.rounding.unset(eOverridePriority::PRIORITY_SET_PROP);
      |              ^~~~~~~~~~~~
src/Render.cpp:114:42: error: 'eOverridePriority' has not been declared
  114 |     pWindow->m_windowData.rounding.unset(eOverridePriority::PRIORITY_SET_PROP);
      |                                          ^~~~~~~~~~~~~~~~~
src/Render.cpp: In member function 'void CHyprspaceWidget::draw()':
src/Render.cpp:189:248: warning: narrowing conversion of 'Config::panelBorderWidth' from 'int' to 'double' [-Wnarrowing]
  189 |         CBox borderBox = {widgetBox.x, owner->m_position.y + (Config::onBottom * owner->m_transformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset->value() * owner->m_scale) * bottomInvert, owner->m_transformedSize.x, Config::panelBorderWidth};
      |                                                                                                                                                                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~~
src/main.cpp: In function 'void onRender(void*, SCallbackInfo&, std::any)':
src/main.cpp:145:36: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
  145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
      |                                    ^~~~~~~~~~~~
src/main.cpp:145:92: error: 'eOverridePriority' has not been declared
  145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
      |                                                                                            ^~~~~~~~~~~~~~~~~
src/main.cpp:145:58: error: 'CWindowOverridableVar' was not declared in this scope
  145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
      |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:149:36: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
  149 |                         curWindow->m_windowData.noBlur.unset(eOverridePriority::PRIORITY_SET_PROP);
      |                                    ^~~~~~~~~~~~
src/main.cpp:149:62: error: 'eOverridePriority' has not been declared
  149 |                         curWindow->m_windowData.noBlur.unset(eOverridePriority::PRIORITY_SET_PROP);
      |                                                              ^~~~~~~~~~~~~~~~~
src/main.cpp: In function 'void onTouchDown(void*, SCallbackInfo&, std::any)':
src/main.cpp:291:68: error: 'class CCompositor' has no member named 'm_lastMonitor'
  291 |     targetMonitor = targetMonitor ? targetMonitor : g_pCompositor->m_lastMonitor.lock();
      |                                                                    ^~~~~~~~~~~~~
make: *** [Makefile:9: all] Error 1
```

Output from `hyprctl version`:
```
Hyprland 0.52.2 built from branch unknown at commit unknown unknown (unknown).
Date: unknown
Tag: unknown, commits: 0

Libraries:
Hyprgraphics: built against 0.4.0, system has unknown
Hyprutils: built against 0.10.4, system has unknown
Hyprcursor: built against 0.1.13, system has unknown
Hyprlang: built against 0.6.7, system has unknown
Aquamarine: built against 0.10.0, system has unknown

no flags were set
```

**Comment by Postboote1** [comment]
Now I changed that nixos builds hyprland from my flake. Now hyprland is on Version 0.52.0 and I get this log:
```bash
error: Cannot build '/nix/store/k75hzjb4sb631z9ymbkpsxwgv26iv2l8-Hyprspace-0.1+date=2025-12-04_0467be8.drv'.
       Reason: builder failed with exit code 2.
       Output paths:
         /nix/store/a9c0nfvl1frkgqdr93sw1aii165rk4il-Hyprspace-0.1+date=2025-12-04_0467be8
       Last 25 log lines:
       > src/Render.cpp: In member function 'void CHyprspaceWidget::draw()':
       > src/Render.cpp:189:248: warning: narrowing conversion of 'Config::panelBorderWidth' from 'int' to 'double' [-Wnarrowing]
       >   189 |         CBox borderBox = {widgetBox.x, owner->m_position.y + (Config::onBottom * owner->m_transformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset->value() * owner->m_scale) * bottomInvert, owner->m_transformedSize.x, Config::panelBorderWidth};
       >       |                                                                                                                                                                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~~
       > src/main.cpp: In function 'void onRender(void*, SCallbackInfo&, std::any)':
       > src/main.cpp:145:36: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
       >   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
       >       |                                    ^~~~~~~~~~~~
       > src/main.cpp:145:92: error: 'eOverridePriority' has not been declared
       >   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
       >       |                                                                                            ^~~~~~~~~~~~~~~~~
       > src/main.cpp:145:58: error: 'CWindowOverridableVar' was not declared in this scope
       >   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
       >       |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
       > src/main.cpp:149:36: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
       >   149 |                         curWindow->m_windowData.noBlur.unset(eOverridePriority::PRIORITY_SET_PROP);
       >       |                                    ^~~~~~~~~~~~
       > src/main.cpp:149:62: error: 'eOverridePriority' has not been declared
       >   149 |                         curWindow->m_windowData.noBlur.unset(eOverridePriority::PRIORITY_SET_PROP);
       >       |                                                              ^~~~~~~~~~~~~~~~~
       > src/main.cpp: In function 'void onTouchDown(void*, SCallbackInfo&, std::any)':
       > src/main.cpp:291:68: error: 'class CCompositor' has no member named 'm_lastMonitor'
       >   291 |     targetMonitor = targetMonitor ? targetMonitor : g_pCompositor->m_lastMonitor.lock();
       >       |                                                                    ^~~~~~~~~~~~~
       > make: *** [Makefile:9: all] Error 1
       For full logs, run:
         nix log /nix/store/k75hzjb4sb631z9ymbkpsxwgv26iv2l8-Hyprspace-0.1+date=2025-12-04_0467be8.drv
```
The errors are also different from #209

**Comment by DavidOlmos03** [comment]
> Cannot build hyprspace on hyprland 0.52.2 on Nixos.
> 
> error: Cannot build '/nix/store/k75hzjb4sb631z9ymbkpsxwgv26iv2l8-Hyprspace-0.1+date=2025-12-04_0467be8.drv'.
>        Reason: builder failed with exit code 2.
>        Output paths:
>          /nix/store/a9c0nfvl1frkgqdr93sw1aii165rk4il-Hyprspace-0.1+date=2025-12-04_0467be8
>        Last 25 log lines:
>        > src/Render.cpp: In member function 'void CHyprspaceWidget::draw()':
>        > src/Render.cpp:189:248: warning: narrowing conversion of 'Config::panelBorderWidth' from 'int' to 'double' [-Wnarrowing]
>        >   189 |         CBox borderBox = {widgetBox.x, owner->m_position.y + (Config::onBottom * owner->m_transformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset->value() * owner->m_scale) * bottomInvert, owner->m_transformedSize.x, Config::panelBorderWidth};
>        >       |                                                                                                                                                                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~~
>        > src/main.cpp: In function 'void onRender(void*, SCallbackInfo&, std::any)':
>        > src/main.cpp:145:36: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
>        >   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
>        >       |                                    ^~~~~~~~~~~~
>        > src/main.cpp:145:92: error: 'eOverridePriority' has not been declared
>        >   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
>        >       |                                                                                            ^~~~~~~~~~~~~~~~~
>        > src/main.cpp:145:58: error: 'CWindowOverridableVar' was not declared in this scope
>        >   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
>        >       |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>        > src/main.cpp:149:36: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
>        >   149 |                         curWindow->m_windowData.noBlur.unset(eOverridePriority::PRIORITY_SET_PROP);
>        >       |                                    ^~~~~~~~~~~~
>        > src/main.cpp:149:62: error: 'eOverridePriority' has not been declared
>        >   149 |                         curWindow->m_windowData.noBlur.unset(eOverridePriority::PRIORITY_SET_PROP);
>        >       |                                                              ^~~~~~~~~~~~~~~~~
>        > src/main.cpp: In function 'void onTouchDown(void*, SCallbackInfo&, std::any)':
>        > src/main.cpp:291:68: error: 'class CCompositor' has no member named 'm_lastMonitor'
>        >   291 |     targetMonitor = targetMonitor ? targetMonitor : g_pCompositor->m_lastMonitor.lock();
>        >       |                                                                    ^~~~~~~~~~~~~
>        > make: *** [Makefile:9: all] Error 1
>        For full logs, run:
>          nix log /nix/store/k75hzjb4sb631z9ymbkpsxwgv26iv2l8-Hyprspace-0.1+date=2025-12-04_0467be8.drv
> Full logs from hyprspace build:
> 
> Running phase: unpackPhase
> @nix { "action": "setPhase", "phase": "unpackPhase" }
> unpacking source archive /nix/store/lplz5ki57q5f0x2fph8nvmm9llj5v64q-1z2w2n5qnm1nq150xr3l4knlimwjv1y0-source
> source root is 1z2w2n5qnm1nq150xr3l4knlimwjv1y0-source
> Running phase: patchPhase
> @nix { "action": "setPhase", "phase": "patchPhase" }
> Running phase: updateAutotoolsGnuConfigScriptsPhase
> @nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
> Running phase: configurePhase
> @nix { "action": "setPhase", "phase": "configurePhase" }
> no configure script, doing nothing
> Running phase: buildPhase
> @nix { "action": "setPhase", "phase": "buildPhase" }
> build flags: SHELL=/nix/store/rlq03x4cwf8zn73hxaxnx0zn5q9kifls-bash-5.3p3/bin/bash
> g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++2b -O2 `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` src/Input.cpp src/Layout.cpp src/Overview.cpp src/Render.cpp src/main.cpp -o Hyprspace.so
> src/Layout.cpp: In member function 'void CHyprspaceWidget::updateLayout()':
> src/Layout.cpp:38:23: error: 'class CMonitor' has no member named 'm_reservedTopLeft'; did you mean 'm_reservedArea'?
>    38 |             pMonitor->m_reservedTopLeft.y = currentHeight;
>       |                       ^~~~~~~~~~~~~~~~~
>       |                       m_reservedArea
> src/Layout.cpp:40:23: error: 'class CMonitor' has no member named 'm_reservedBottomRight'
>    40 |             pMonitor->m_reservedBottomRight.y = currentHeight;
>       |                       ^~~~~~~~~~~~~~~~~~~~~
> src/Overview.cpp: In member function 'void CHyprspaceWidget::show()':
> src/Overview.cpp:44:64: error: 'SFullscreenState' was not declared in this scope; did you mean Desktop::View::SFullscreenState'?
>    44 |                     g_pCompositor->setWindowFullscreenState(w, SFullscreenState{.internal = FSMODE_NONE, .client = FSMODE_NONE});
>       |                                                                ^~~~~~~~~~~~~~~~
>       |                                                                Desktop::View::SFullscreenState
> In file included from /nix/store/6fz8hr6nvnmxj5nc2b73wdcmk3lqbk3b-hyprland-0.52.0+date=2025-12-13_09e195d-dev/include/hyprland/src/Compositor.hpp:10,
>                  from src/Overview.hpp:2,
>                  from src/Overview.cpp:1:
> /nix/store/6fz8hr6nvnmxj5nc2b73wdcmk3lqbk3b-hyprland-0.52.0+date=2025-12-13_09e195d-dev/include/hyprland/src/desktop/view/Window.hpp:69:12: note: 'Desktop::View::SFullscreenState' declared here
>    69 |     struct SFullscreenState {
>       |            ^~~~~~~~~~~~~~~~
> src/Overview.cpp: In member function 'void CHyprspaceWidget::hide()':
> src/Overview.cpp:111:52: error: 'SFullscreenState' was not declared in this scope; did you mean 'Desktop::View::SFullscreenState'?
>   111 |         g_pCompositor->setWindowFullscreenState(w, SFullscreenState(oFullscreenMode));
>       |                                                    ^~~~~~~~~~~~~~~~
>       |                                                    Desktop::View::SFullscreenState
> /nix/store/6fz8hr6nvnmxj5nc2b73wdcmk3lqbk3b-hyprland-0.52.0+date=2025-12-13_09e195d-dev/include/hyprland/src/desktop/view/Window.hpp:69:12: note: 'Desktop::View::SFullscreenState' declared here
>    69 |     struct SFullscreenState {
>       |            ^~~~~~~~~~~~~~~~
> src/Render.cpp: In function 'void renderWindowStub(PHLWINDOW, PHLMONITOR, PHLWORKSPACE, Hyprutils::Math::CBox, timespec*)':
> src/Render.cpp:76:47: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
>    76 |     const auto oUseNearestNeighbor = pWindow->m_windowData.nearestNeighbor;
>       |                                               ^~~~~~~~~~~~
> src/Render.cpp:90:34: error: 'SFullscreenState' was not declared in this scope; did you mean 'Desktop::View::SFullscreenState'?
>    90 |     pWindow->m_fullscreenState = SFullscreenState{FSMODE_NONE};
>       |                                  ^~~~~~~~~~~~~~~~
>       |                                  Desktop::View::SFullscreenState
> In file included from /nix/store/6fz8hr6nvnmxj5nc2b73wdcmk3lqbk3b-hyprland-0.52.0+date=2025-12-13_09e195d-dev/include/hyprland/src/Compositor.hpp:10,
>                  from src/Overview.hpp:2,
>                  from src/Render.cpp:1:
> /nix/store/6fz8hr6nvnmxj5nc2b73wdcmk3lqbk3b-hyprland-0.52.0+date=2025-12-13_09e195d-dev/include/hyprland/src/desktop/view/Window.hpp:69:12: note: 'Desktop::View::SFullscreenState' declared here
>    69 |     struct SFullscreenState {
>       |            ^~~~~~~~~~~~~~~~
> src/Render.cpp:91:14: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
>    91 |     pWindow->m_windowData.nearestNeighbor = false;
>       |              ^~~~~~~~~~~~
> src/Render.cpp:94:14: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
>    94 |     pWindow->m_windowData.rounding = CWindowOverridableVar<Hyprlang::INT>(pWindow->rounding() * curScaling * pMonitor->m_scale, eOverridePriority::PRIORITY_SET_PROP);
>       |              ^~~~~~~~~~~~
> src/Render.cpp:94:129: error: 'eOverridePriority' has not been declared
>    94 |     pWindow->m_windowData.rounding = CWindowOverridableVar<Hyprlang::INT>(pWindow->rounding() * curScaling * pMonitor->m_scale, eOverridePriority::PRIORITY_SET_PROP);
>       |                                                                                                                                 ^~~~~~~~~~~~~~~~~
> src/Render.cpp:94:38: error: 'CWindowOverridableVar' was not declared in this scope
>    94 |     pWindow->m_windowData.rounding = CWindowOverridableVar<Hyprlang::INT>(pWindow->rounding() * curScaling * pMonitor->m_scale, eOverridePriority::PRIORITY_SET_PROP);
>       |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/Render.cpp:111:14: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
>   111 |     pWindow->m_windowData.nearestNeighbor = oUseNearestNeighbor;
>       |              ^~~~~~~~~~~~
> src/Render.cpp:114:14: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
>   114 |     pWindow->m_windowData.rounding.unset(eOverridePriority::PRIORITY_SET_PROP);
>       |              ^~~~~~~~~~~~
> src/Render.cpp:114:42: error: 'eOverridePriority' has not been declared
>   114 |     pWindow->m_windowData.rounding.unset(eOverridePriority::PRIORITY_SET_PROP);
>       |                                          ^~~~~~~~~~~~~~~~~
> src/Render.cpp: In member function 'void CHyprspaceWidget::draw()':
> src/Render.cpp:189:248: warning: narrowing conversion of 'Config::panelBorderWidth' from 'int' to 'double' [-Wnarrowing]
>   189 |         CBox borderBox = {widgetBox.x, owner->m_position.y + (Config::onBottom * owner->m_transformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset->value() * owner->m_scale) * bottomInvert, owner->m_transformedSize.x, Config::panelBorderWidth};
>       |                                                                                                                                                                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~~
> src/main.cpp: In function 'void onRender(void*, SCallbackInfo&, std::any)':
> src/main.cpp:145:36: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
>   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
>       |                                    ^~~~~~~~~~~~
> src/main.cpp:145:92: error: 'eOverridePriority' has not been declared
>   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
>       |                                                                                            ^~~~~~~~~~~~~~~~~
> src/main.cpp:145:58: error: 'CWindowOverridableVar' was not declared in this scope
>   145 |                         curWindow->m_windowData.noBlur = CWindowOverridableVar<bool>(true, eOverridePriority::PRIORITY_SET_PROP);
>       |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/main.cpp:149:36: error: 'class Desktop::View::CWindow' has no member named 'm_windowData'
>   149 |                         curWindow->m_windowData.noBlur.unset(eOverridePriority::PRIORITY_SET_PROP);
>       |                                    ^~~~~~~~~~~~
> src/main.cpp:149:62: error: 'eOverridePriority' has not been declared
>   149 |                         curWindow->m_windowData.noBlur.unset(eOverridePriority::PRIORITY_SET_PROP);
>       |                                                              ^~~~~~~~~~~~~~~~~
> src/main.cpp: In function 'void onTouchDown(void*, SCallbackInfo&, std::any)':
> src/main.cpp:291:68: error: 'class CCompositor' has no member named 'm_lastMonitor'
>   291 |     targetMonitor = targetMonitor ? targetMonitor : g_pCompositor->m_lastMonitor.lock();
>       |                                                                    ^~~~~~~~~~~~~
> make: *** [Makefile:9: all] Error 1
> Output from `hyprctl version`:
> 
> ```
> Hyprland 0.52.2 built from branch unknown at commit unknown unknown (unknown).
> Date: unknown
> Tag: unknown, commits: 0
> 
> Libraries:
> Hyprgraphics: built against 0.4.0, system has unknown
> Hyprutils: built against 0.10.4, system has unknown
> Hyprcursor: built against 0.1.13, system has unknown
> Hyprlang: built against 0.6.7, system has unknown
> Aquamarine: built against 0.10.0, system has unknown
> 
> no flags were set
> ```

I’m on the same Hyprland version (and ml4w dotfiles) and fixed this with a manual install. Clone the repo into ~/.config/hypr/plugins, run make all, load it with `hyprctl plugin load ~/.config/hypr/plugins/Hyprspace/Hyprspace.so`, confirm with hyprctl plugins list, then  add to `~/.config/hypr/conf/custom.conf` this line `bind = $mainMod, L, exec, hyprctl dispatch overview:toggle` and finally try SUPER + L to start.

Works fine for me.
