### PR TITLE
feat: Hyprland 0.54.0 compatibility

### PR DESCRIPTION
**Pull request by douglas**
## Summary

Hyprland 0.54.0 introduces several breaking API changes. This PR updates Hyprspace to be compatible with the new APIs.

### Breaking changes addressed

- **Event system rewrite**: `registerCallbackDynamic()` is deprecated (now a no-op). Migrated all 15 event hooks to the new typed `Event::bus()->m_events.*.listen()` system using `CHyprSignalListener` handles. All handlers now receive typed arguments directly instead of `std::any`.

- **Layout system rewrite**: `g_pLayoutManager->getCurrentLayout()` was removed. Replaced with `g_layoutManager->recalculateMonitor(PHLMONITOR)` which now takes a monitor handle instead of a monitor ID.

- **Drag state moved**: `g_pInputManager->m_currentlyDraggedWindow` and `m_dragMode` no longer exist on InputManager. Replaced with `g_layoutManager->dragController()->target()->window()` and `g_layoutManager->endDragTarget()`.

- **Renderer signatures**: `renderWindow`/`renderLayer` now use `Time::steady_tp` instead of `timespec*`. `renderLayer` takes `PHLLS` instead of `PHLLSREF` and has a new `lockscreen` parameter.

- **Keyboard event**: No longer packed in `std::unordered_map<std::string, std::any>`. Handler receives `IKeyboard::SKeyEvent` directly, keyboard obtained via `g_pSeatManager->m_keyboard`.

- **Mouse axis event**: No longer wrapped in a map. Handler receives `IPointer::SAxisEvent` directly.

- **Touch events**: All touch handlers updated to receive typed event structs directly (`SDownEvent`, `SMotionEvent`, `SUpEvent`).

### Commits

Organized as atomic, incremental changes:

1. **Update includes and typedefs** — Foundation changes in `Globals.hpp`
2. **Update render stubs** — New time types, remove drag trick hack from `Render.cpp`
3. **New layout manager API** — `recalculateMonitor` changes in `Layout.cpp`
4. **Drag controller API** — New drag state access in `Input.cpp`
5. **Event bus migration** — Full event system rewrite in `main.cpp`

## Test plan

- [ ] Build with `make all` against Hyprland 0.54.0 headers (verified locally)
- [ ] Load plugin in Hyprland 0.54.0 and verify overview opens/closes
- [ ] Verify windows render correctly in overview
- [ ] Verify mouse click, drag, and scroll interactions
- [ ] Verify swipe gestures work
- [ ] Verify keyboard exit works
- [ ] Verify workspace switching from overview
- [ ] Verify multi-monitor support

### CODE REVIEW

**Comment by noisesfromspace** [comment]
I really tried but couldn't get this working on NixOS with 0.54. Several glitches, making changes to your code I got the stage where it would shortly show the overview. It's mostly pushing down my waybar/windows and then staying stuck here.

Hopefully someone else can also test and maybe find where things go wrong..

**Comment by jemabaris** [comment]
Kinda same for me. After some hustle I managed to build, load and run the plugin but it also pushes waybar down and leaves it there and it will only work without any other open tiles. As soon as there's only one other tile open, toggling Hyprspace will crash Hyprland and throw me into the fallback config. It also crashes when clicking around on the workspace overlays a bunch. 

This is under Arch EndeavourOS btw.

https://github.com/user-attachments/assets/fa6126eb-e6ef-4e35-8866-c0e384c0f5ac

**Comment by onyx-tty** [comment]
@jemabaris The same thing happened to me yesterday when I enabled it, and it made me wonder if it's something on my side! Thank you for the recording, it's going to help clarify the issue.

**Comment by acidclouds** [comment]
A workaround for the effects shown in this video recording:

plugin:overview:affectStrut = false

**Comment by jemabaris** [comment]
> A workaround for the effects shown in this video recording:
> 
> plugin:overview:affectStrut = false

This fixes Waybar being pushed down but the rest is still broken. Toggling Hyprspace with any other app open immediately crashes, so still unusable.

**Comment by koku17** [comment]
I'm on latest version of hyprland and getting the same library errors when compiling

### Hyprland details
```
$ hyprland -v
Hyprland 0.54.1 built from branch v0.54.1 at commit 4b07770b9ef1cceb2e6f56d33538aaffb9186b9c clean ([gha] Nix: update inputs).
Date: Tue Mar 3 21:06:41 2026
Tag: v0.54.1, commits: 6979

Libraries:
Hyprgraphics: built against 0.5.0, system has 0.5.0
Hyprutils: built against 0.11.0, system has 0.11.0
Hyprcursor: built against 0.1.13, system has 0.1.13
Hyprlang: built against 0.6.8, system has 0.6.8
Aquamarine: built against 0.10.0, system has 0.10.0

Version ABI string: 4b07770b9ef1cceb2e6f56d33538aaffb9186b9c_aq_0.10_hu_0.11_hg_0.5_hc_0.1_hlg_0.6
no flags were set
```

### Building Plugin
```
$ hpyrpm update -v
...
→ Cloning https://github.com/KZDKM/Hyprspace
✔ cloned
✔ found hyprpm manifest
✔ parsed manifest, found 1 plugins:
→ Hyprspace by KZdkm version
→ Manifest has 17 pins, checking
✔ Hyprland headers OK
→ Building Hyprspace
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /run/user/1000/hyprpm/user && PKG_CONFIG_PATH="/var/cache/hyprpm/user/headersRoot/share/pkgconfig:$PKG_CONFIG_PATH" make all
g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++2b -O2 `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` src/Input.cpp src/Layout.cpp src/main.cpp src/Overview.cpp src/Render.cpp -o Hyprspace.so
In file included from src/Input.cpp:2:
src/Globals.hpp:8:10: fatal error: hyprland/src/managers/LayoutManager.hpp: No such file or directory
    8 | #include <hyprland/src/managers/LayoutManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/Layout.cpp:2:
src/Globals.hpp:8:10: fatal error: hyprland/src/managers/LayoutManager.hpp: No such file or directory
    8 | #include <hyprland/src/managers/LayoutManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/main.cpp:6:
src/Globals.hpp:8:10: fatal error: hyprland/src/managers/LayoutManager.hpp: No such file or directory
    8 | #include <hyprland/src/managers/LayoutManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/Overview.cpp:2:
src/Globals.hpp:8:10: fatal error: hyprland/src/managers/LayoutManager.hpp: No such file or directory
    8 | #include <hyprland/src/managers/LayoutManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/Render.cpp:2:
src/Globals.hpp:8:10: fatal error: hyprland/src/managers/LayoutManager.hpp: No such file or directory
    8 | #include <hyprland/src/managers/LayoutManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:9: all] Error 1
...
```

**Comment by pascal-fischer** [comment]
I did continue a bit on this one. I made it work for me quite stable. I am running on EnveavourOS as well. https://github.com/KZDKM/Hyprspace/compare/main...pascal-fischer:Hyprspace:main 
Would be nice to collect some feedback from other platforms.

**Comment by 0xl30** [comment]
> I did continue a bit on this one. I made it work for me quite stable. I am running on EnveavourOS as well. [main...pascal-fischer:Hyprspace:main](https://github.com/KZDKM/Hyprspace/compare/main...pascal-fischer:Hyprspace:main) Would be nice to collect some feedback from other platforms.

Thanks Bro It's Work  :+1: 
on my arch linux 
(Create New PR For Easy To Build And Find Your Commit )

**Comment by noisesfromspace** [comment]
> I did continue a bit on this one. I made it work for me quite stable. I am running on EnveavourOS as well. [main...pascal-fischer:Hyprspace:main](https://github.com/KZDKM/Hyprspace/compare/main...pascal-fischer:Hyprspace:main) Would be nice to collect some feedback from other platforms.

I got it working on NixOS with Hyprland 54.2. :trophy: 

Now for the weirdness: When I first login to my session the plugin is unusable, windows become opaque, the overview shows 1 workspace glitching every time I `:toggle` or `:open`. I tried making a screenshot of this behavior and run grim from the command line, it starts working... Same with recording my screen with Kooha, I can reproduce this behavior by logging in and out..

https://github.com/user-attachments/assets/814a8e1a-36ea-4e67-be11-000cc14d0aec

Any wizzards that could explain what is going on? Do these recording apps somehow refresh something in the Wayland protocol that makes this start working? Tried rebooting, reloading wayland config. Different amount of applications that are started. Happy for now at least.

**Comment by douglas** [comment]
Hello folks! I added a bunch of other commits, but since I'm using `hyprtasking` I didn't do a very extensive test, so if you can, please test it so we know it is stable.

I also tried to support Hyperland 0.54.0, 0.54.1 and 0.54.2, lets see how it goes =)

**Comment by noisesfromspace** [comment]
Still crashing with the new additions for me, attached the logs. 

[hyprlandCrashReport56952.txt](https://github.com/user-attachments/files/25976383/hyprlandCrashReport56952.txt)

**Comment by douglas** [comment]
@martijnboers Thanks for the detailed backtrace — that was exactly what was needed to track this down.

The crash is caused by `findFunctionsByName("renderWindow")` returning all symbols with that name across all translation units, including `Screenshare::CScreenshareFrame::renderWindow()`. On your system that symbol sorts before `CHyprRenderer::renderWindow()`, so `pRenderWindow` ends up pointing at the wrong function.

Fix is in commit ec0f45d on the `support_hyprland_0_54_0` branch: switched to `findFunctionBySymbol()` which filters by demangled class name, so only `CHyprRenderer::renderWindow` is selected.

Could you rebuild from `support_hyprland_0_54_0` and let me know if the crash is gone?

**Comment by jemabaris** [comment]
Thank you for your fixes, Douglas. Now we're definitely getting somewhere. Although it's still not quite working out for me. Pretty much any other app's window, except for the terminal's glitch out shortly after toggling Hyprspace. It's much better though than before, where doing so would immediately result in a crash. 
See the video attached. If I can anyhow provide you with any additional information you need for further troubleshooting please let me know. 

https://github.com/user-attachments/assets/4b71357c-838a-40bd-a2a6-cb880597f815

**Comment by jemabaris** [comment]
Small update: I just realized that, similar to the description of another user on here, the issue with the disappearing windows seems to be gone after taking a screenshot once. It really looks like taking a screenshot or video wakes up something that's needed for hyprspace to function fully.

**Comment by jemabaris** [comment]
@douglas I just rebuilt with the changes in your latest commit but the problem still persists sadly. Maybe I made a mistake, idk, but I couldn't see any improvement of the disappearing window glitch. I've rebuilt it even a second time to make sure but without success.
Taking a single screenshot with hypershot still seems to completely fix the issue until the next reboot.

**Comment by douglas** [comment]
@jemabaris The disappearing windows issue you're describing (fixed by taking a screenshot) is exactly what the latest commit `586b095` targets.

The root cause: `hide()` wasn't calling `damageMonitor()`, and once the close animation finished, `draw()` would stop running (early return when `!active && !isBeingAnimated()`), leaving the compositor with stale render state. Taking a screenshot forces a full `damageMonitor()` call via screencopy, which is why that fixed it.

The fix adds two things:
1. An explicit `damageMonitor()` + `scheduleFrameForMonitor()` in `hide()` (matching what `show()` already did)
2. A `setCallbackOnEnd` callback on the `curYOffset` animation that fires one final `damageMonitor()` after the close animation completes

Could you rebuild from the `support_hyprland_0_54_0` branch and let me know if the window glitch is gone?

**Comment by jemabaris** [comment]
@douglas  I wrote my last message after rebuilding with commit 586b095 and wanted to let you know that it sadly didn't fix the issues I've been experiencing with the glitching windows yet.

**Comment by jemabaris** [comment]
@douglas I just did another build with the latest changes and the issue still persists. It's interesting though that you don't seem to have these issues yourself. Wonder why that is?

**Comment by noisesfromspace** [comment]
With the latest changes it's no longer crashing which is nice! Also don't have to run `grim` etc. I can no longer re-arrange windows though? Is this something you experience? 

Running with:
```
        plugin.overview = {
          affectStrut = false; # re-renders citrix
          hideBackgroundLayers = true;
          hideTopLayers = true;
          hideOverlayLayers = true;
          hideRealLayers = true;
        };
```

**Comment by develcooking** [comment]
So i tried to compile it with hyprland v0.54.2 compiled manually compiled on fedora but get those erros with your branch


Hope it isn't that hard to read the errorlog due to it is in german
```bash
jp@fedora:~/hyprland-build/Hyprland$ git clone https://github.com/douglas/Hyprspace.git
Klone nach 'Hyprspace'...
remote: Enumerating objects: 1124, done.
remote: Counting objects: 100% (568/568), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 1124 (delta 514), reused 500 (delta 481), pack-reused 556 (from 2)
Empfange Objekte: 100% (1124/1124), 253.52 KiB | 3.67 MiB/s, fertig.
Löse Unterschiede auf: 100% (766/766), fertig.
jp@fedora:~/hyprland-build/Hyprland$ cd Hyprspace/
jp@fedora:~/hyprland-build/Hyprland/Hyprspace$ make all
g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++2b -O2 `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` src/Input.cpp src/Layout.cpp src/main.cpp src/Overview.cpp src/Render.cpp -o Hyprspace.so
In Datei, eingebunden von src/Input.cpp:2:
src/Globals.hpp:8:10: schwerwiegender Fehler: hyprland/src/managers/LayoutManager.hpp: Datei oder Verzeichnis nicht gefunden
    8 | #include <hyprland/src/managers/LayoutManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
In Datei, eingebunden von src/Layout.cpp:2:
src/Globals.hpp:8:10: schwerwiegender Fehler: hyprland/src/managers/LayoutManager.hpp: Datei oder Verzeichnis nicht gefunden
    8 | #include <hyprland/src/managers/LayoutManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
In Datei, eingebunden von src/main.cpp:6:
src/Globals.hpp:8:10: schwerwiegender Fehler: hyprland/src/managers/LayoutManager.hpp: Datei oder Verzeichnis nicht gefunden
    8 | #include <hyprland/src/managers/LayoutManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
In Datei, eingebunden von src/Overview.cpp:2:
src/Globals.hpp:8:10: schwerwiegender Fehler: hyprland/src/managers/LayoutManager.hpp: Datei oder Verzeichnis nicht gefunden
    8 | #include <hyprland/src/managers/LayoutManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
In Datei, eingebunden von src/Render.cpp:2:
src/Globals.hpp:8:10: schwerwiegender Fehler: hyprland/src/managers/LayoutManager.hpp: Datei oder Verzeichnis nicht gefunden
    8 | #include <hyprland/src/managers/LayoutManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
make: *** [Makefile:9: all] Fehler 1

```

**Comment by jemabaris** [comment]
Since the latest hyprland updates hyprspace doesn't seam to work at all anymore for me. I rebuilt from source after the hyprland updates but now as soon as I load the plugin hyprland crashes instantly. 
How's it going for you, @douglas ?

**Comment by 0xl30** [comment]
> Since the latest hyprland updates hyprspace doesn't seam to work at all anymore for me. I rebuilt from source after the hyprland updates but now as soon as I load the plugin hyprland crashes instantly. How's it going for you, @douglas ?

I have implemented a temporary fix,You may use this workaround until a stable update is available
https://github.com/0xl30/Hyprspace

**Comment by jemabaris** [comment]
@0xl30  Thank you man! That works great and it doesn't even require me to take a screenshot before things work properly 😆

EDIT: I take that screenshot bit back^^ That workaround is still needed for most window types. I just had an electron app open when testing and that wouldn't disappear but other windows like Firefox still do... Until I take a scrennshot XD

**Comment by KZDKM** [comment]
Thank you for the fix! I apologize for not being attentive in watching PRs as I have been swamped with school work recently.
