### ISSUE TITLE
Fails to build on v0.46.2

### ISSUE THREAD

**Issue by SorcierMaheP** [KZDKM/Hyprspace#127]
Hello! The Hyprspace plugin does not build against Hyprland v0.46.2. The hyprland version and error log is provided below:
```Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1
```

```
g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++2b -O2 `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` src/Input.cpp src/Layout.cpp src/main.cpp src/Overview.cpp src/Render.cpp -o Hyprspace.so
src/main.cpp: In function ‘PLUGIN_DESCRIPTION_INFO pluginInit(void*)’:
src/main.cpp:473:18: error: ‘addDispatcherV2’ is not a member of ‘HyprlandAPI’; did you mean ‘addDispatcher’?
  473 |     HyprlandAPI::addDispatcherV2(pHandle, "overview:toggle", ::dispatchToggleOverview);
      |                  ^~~~~~~~~~~~~~~
      |                  addDispatcher
src/main.cpp:474:18: error: ‘addDispatcherV2’ is not a member of ‘HyprlandAPI’; did you mean ‘addDispatcher’?
  474 |     HyprlandAPI::addDispatcherV2(pHandle, "overview:open", ::dispatchOpenOverview);
      |                  ^~~~~~~~~~~~~~~
      |                  addDispatcher
src/main.cpp:475:18: error: ‘addDispatcherV2’ is not a member of ‘HyprlandAPI’; did you mean ‘addDispatcher’?
  475 |     HyprlandAPI::addDispatcherV2(pHandle, "overview:close", ::dispatchCloseOverview);
      |                  ^~~~~~~~~~~~~~~
      |                  addDispatcher
src/main.cpp: At global scope:
src/main.cpp:328:24: warning: ‘SDispatchResult dispatchCloseOverview(std::string)’ defined but not used [-Wunused-function]
  328 | static SDispatchResult dispatchCloseOverview(std::string arg) {
      |                        ^~~~~~~~~~~~~~~~~~~~~
src/main.cpp:313:24: warning: ‘SDispatchResult dispatchOpenOverview(std::string)’ defined but not used [-Wunused-function]
  313 | static SDispatchResult dispatchOpenOverview(std::string arg) {
      |                        ^~~~~~~~~~~~~~~~~~~~
src/main.cpp:287:24: warning: ‘SDispatchResult dispatchToggleOverview(std::string)’ defined but not used [-Wunused-function]
  287 | static SDispatchResult dispatchToggleOverview(std::string arg) {
      |                        ^~~~~~~~~~~~~~~~~~~~~~
src/Render.cpp: In member function ‘void CHyprspaceWidget::draw()’:
src/Render.cpp:122:248: warning: narrowing conversion of ‘Config::panelBorderWidth’ from ‘int’ to ‘double’ [-Wnarrowing]
  122 |         CBox borderBox = {widgetBox.x, owner->vecPosition.y + (Config::onBottom * owner->vecTransformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset.value() * owner->scale) * bottomInvert, owner->vecTransformedSize.x, Config::panelBorderWidth};
      |                                                                                                                                                                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~~
make: *** [Makefile:7: all] Error 1
```

I believe this is due to register dispatcher v2, which is not a part of v0.46.2.

**Comment by Drllap** [comment]
I'm running into the same issue

**Comment by myamusashi** [comment]
[This pin](https://github.com/KZDKM/Hyprspace/blob/main/hyprpm.toml) only loads hyprland up to 0.45.2

**Comment by noahfraiture** [comment]
> `$ sed src/main.cpp -e 's/addDispatcherV2/addDispatcher/g'`

Is it the only thing ? Can I just make a PR that make this change ? It's pretty annoying

**Comment by myamusashi** [comment]
https://github.com/KZDKM/Hyprspace/pull/130

**Comment by 0x313** [comment]
> > `$ sed src/main.cpp -e 's/addDispatcherV2/addDispatcher/g'`
> 
> Is it the only thing ? Can I just make a PR that make this change ? It's pretty annoying

already done, #129

**Comment by noahfraiture** [comment]
Hello, the PR has been merged and hyprspace build, but it still doesn't work. 
On the command/motion, the window on the screen disappears, and nothing show up

**Comment by myamusashi** [comment]
> Hello, the PR has been merged and hyprspace build, but it still doesn't work. On the command/motion, the window on the screen disappears, and nothing show up

Hyprland just rewriting the rendering schedule https://github.com/hyprwm/Hyprland/commit/e536b02248f370971716b744968776f6880528be

**Comment by noahfraiture** [comment]
> > Hello, the PR has been merged and hyprspace build, but it still doesn't work. On the command/motion, the window on the screen disappears, and nothing show up
> 
> Hyprland just rewriting the rendering schedule https://github.com/hyprwm/Hyprland/commit/e536b02248f370971716b744968776f6880528be

Oh ok. I guess we'll wait next update

**Comment by Acebasein** [comment]
I'm also facing this issue after the recent upgrade to **Hyprland 0.46.2**.  Waiting for the updated Hyprspace version.

Thanks

**Comment by myamusashi** [comment]
Should be working now

**Comment by noahfraiture** [comment]
I actually have a build problem still with the latest flake of hyprland and hyprspace :
```
error: builder for '/nix/store/aady1gyggys2s278clq9d6bzlqvc2sip-Hyprspace-0.1+date=2025-01-18_1b5865f.drv' failed with exit code 1;
       last 25 log lines:
       >     5 | class CLayerSurface;
       >       |       ^~~~~~~~~~~~~
       > ../src/Render.cpp:310:183: error: could not convert '{<expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'Hyprutils::Math::CBox'
       >   310 |                     CBox layerBox = {curWorkspaceBox.pos() + (ls->realPosition->value() - owner->vecPosition) * monitorSizeScaleFactor, ls->realSize->value() * monitorSizeScaleFactor};
       >       |                                                                                                                                                                                       ^
       >       |                                                                                                                                                                                       |
       >       |                                                                                                                                                                                       <brace-enclosed initializer list>
       > ../src/Render.cpp:318:65: error: invalid use of incomplete type 'class CLayerSurface'
       >   318 |                     CBox layerBox = {curWorkspaceBox.pos() + (ls->realPosition->value() - owner->vecPosition) * monitorSizeScaleFactor, ls->realSize->value() * monitorSizeScaleFactor};
       >       |                                                                 ^~
       > /nix/store/4fzrc2drmnh5c9z96h2gnx0z0z0c8dkq-hyprland-0.46.0+date=2025-01-20_a661203-dev/include/hyprland/src/desktop/DesktopTypes.hpp:5:7: note: forward declaration of 'class CLayerSurface'
       >     5 | class CLayerSurface;
       >       |       ^~~~~~~~~~~~~
       > ../src/Render.cpp:318:139: error: invalid use of incomplete type 'class CLayerSurface'
       >   318 |                     CBox layerBox = {curWorkspaceBox.pos() + (ls->realPosition->value() - owner->vecPosition) * monitorSizeScaleFactor, ls->realSize->value() * monitorSizeScaleFactor};
       >       |                                                                                                                                           ^~
       > /nix/store/4fzrc2drmnh5c9z96h2gnx0z0z0c8dkq-hyprland-0.46.0+date=2025-01-20_a661203-dev/include/hyprland/src/desktop/DesktopTypes.hpp:5:7: note: forward declaration of 'class CLayerSurface'
       >     5 | class CLayerSurface;
       >       |       ^~~~~~~~~~~~~
       > ../src/Render.cpp:318:183: error: could not convert '{<expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'Hyprutils::Math::CBox'
       >   318 |                     CBox layerBox = {curWorkspaceBox.pos() + (ls->realPosition->value() - owner->vecPosition) * monitorSizeScaleFactor, ls->realSize->value() * monitorSizeScaleFactor};
       >       |                                                                                                                                                                                       ^
       >       |                                                                                                                                                                                       |
       >       |                                                                                                                                                                                       <brace-enclosed initializer list>
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/aady1gyggys2s278clq9d6bzlqvc2sip-Hyprspace-0.1+date=2025-01-18_1b5865f.drv'.
```

**Comment by myamusashi** [comment]
I recommend you to use hyprland 0.46.2 for now because hyprspace has problems with the latest hyprland

**Comment by noahfraiture** [comment]
Also an error on build 
```
> [5/6] Compiling C++ object libHyprspace.so.p/src_Render.cpp.o
       > ../src/Render.cpp: In member function 'void CHyprspaceWidget::draw()':
       > ../src/Render.cpp:122:248: warning: narrowing conversion of 'Config::panelBorderWidth' from 'int' to 'double' [-Wnarrowing]
       >   122 |         CBox borderBox = {widgetBox.x, owner->vecPosition.y + (Config::onBottom * owner->vecTransformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset.value() * owner->scale) * bottomInvert, owner->vecTransformedSize.x, Config::panelBorderWidth};
       >       |                                                                                                                                                                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~~
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/5jhj6asmpprwh02dsbszi9gr2hja192x-Hyprspace-0.1+date=2024-12-20_6d49cb4.drv'.
```

**Comment by myamusashi** [comment]
Ok that's weird actually, it should just be a warning during compilation.

**Comment by myamusashi** [comment]
> Also an error on build
> 
> ```
> > [5/6] Compiling C++ object libHyprspace.so.p/src_Render.cpp.o
>        > ../src/Render.cpp: In member function 'void CHyprspaceWidget::draw()':
>        > ../src/Render.cpp:122:248: warning: narrowing conversion of 'Config::panelBorderWidth' from 'int' to 'double' [-Wnarrowing]
>        >   122 |         CBox borderBox = {widgetBox.x, owner->vecPosition.y + (Config::onBottom * owner->vecTransformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset.value() * owner->scale) * bottomInvert, owner->vecTransformedSize.x, Config::panelBorderWidth};
>        >       |                                                                                                                                                                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~~
>        > ninja: build stopped: subcommand failed.
>        For full logs, run 'nix log /nix/store/5jhj6asmpprwh02dsbszi9gr2hja192x-Hyprspace-0.1+date=2024-12-20_6d49cb4.drv'.
> ```

Tried it on my machine and it worked, idk why you got that error

**Comment by noahfraiture** [comment]
I must have done something wrong. This is my flake inputs related : 
```
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    hyprland.url = "github:hyprwm/Hyprland/?ref=v0.46.2";

    hyprspace = {
      url = "github:KZDKM/Hyprspace";
      inputs.hyprland.follows = "hyprland";
    };

```
And I simply then `nix flake update hyprspace nixpkgs` then rebuild
Could you help me ? @myamusashi

**Comment by myamusashi** [comment]
Give me the log 
> nix log /nix/store/5jhj6asmpprwh02dsbszi9gr2hja192x-Hyprspace-0.1+date=2024-12-20_6d49cb4.drv

**Comment by myamusashi** [comment]
You can install like this

```
github:KZDKM/Hyprspace?rev=2e65942413a78251e4f070b06f7a515125e96afc
```

**Comment by noahfraiture** [comment]
Oh good this commit works, thank you ! 
I could be good to add version tag i think
