### ISSUE TITLE
Failed to build on 0.41.0

### ISSUE THREAD

**Issue by James-Randall-14** [KZDKM/Hyprspace#64]
Hello, I am unable to build on Hyprland (non-git) 0.41.0. I also tried on 0.41.2, both versions with and without HyprPM.

Please LMK if you need any more information.

```
✔ adding a new plugin repository from https://github.com/KZDKM/Hyprspace
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] y

 → Cloning https://github.com/KZDKM/Hyprspace
✔ cloned
✔ found hyprpm manifest
✔ parsed manifest, found 1 plugins:
 → Hyprspace by KZdkm version
 → Manifest has 2 pins, checking
✔ Hyprland headers OK
 → Building Hyprspace
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/james && PKG_CONFIG_PATH="/home/james/.local/share/hyprpm/headersRoot/share/pkgconfig" make all
g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++2b -O2 `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` src/Input.cpp src/Layout.cpp src/main.cpp src/Overview.cpp src/Render.cpp -o Hyprspace.so
In file included from src/Input.cpp:1:
src/Overview.hpp:22:28: error: ‘Hyprutils’ was not declared in this scope
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                            ^~~~~~~~~
src/Overview.hpp:22:81: error: template argument 1 is invalid
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                                                                                 ^~
src/Overview.hpp:22:84: error: template argument 1 is invalid
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                                                                                    ^~~~~~~~~~~
src/Overview.hpp:22:84: error: template argument 2 is invalid
src/Overview.hpp:22:10: error: ‘<expression error>’ in namespace ‘std’ does not name a type
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/Input.cpp:2:
src/Globals.hpp:14:37: error: ‘Hyprutils’ has not been declared
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                     ^~~~~~~~~
src/Globals.hpp:14:83: error: expected unqualified-id before ‘,’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                                                                   ^
src/Globals.hpp:14:83: error: expected ‘)’ before ‘,’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                             ~                                                     ^
      |                                                                                   )
src/Globals.hpp:14:93: error: expected initializer before ‘*’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                                                                             ^
In file included from src/Layout.cpp:1:
src/Overview.hpp:22:28: error: ‘Hyprutils’ was not declared in this scope
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                            ^~~~~~~~~
src/Overview.hpp:22:81: error: template argument 1 is invalid
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                                                                                 ^~
src/Overview.hpp:22:84: error: template argument 1 is invalid
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                                                                                    ^~~~~~~~~~~
src/Overview.hpp:22:84: error: template argument 2 is invalid
src/Overview.hpp:22:10: error: ‘<expression error>’ in namespace ‘std’ does not name a type
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/Layout.cpp:2:
src/Globals.hpp:14:37: error: ‘Hyprutils’ has not been declared
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                     ^~~~~~~~~
src/Globals.hpp:14:83: error: expected unqualified-id before ‘,’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                                                                   ^
src/Globals.hpp:14:83: error: expected ‘)’ before ‘,’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                             ~                                                     ^
      |                                                                                   )
src/Globals.hpp:14:93: error: expected initializer before ‘*’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                                                                             ^
In file included from src/main.cpp:4:
src/Overview.hpp:22:28: error: ‘Hyprutils’ was not declared in this scope
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                            ^~~~~~~~~
src/Overview.hpp:22:81: error: template argument 1 is invalid
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                                                                                 ^~
src/Overview.hpp:22:84: error: template argument 1 is invalid
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                                                                                    ^~~~~~~~~~~
src/Overview.hpp:22:84: error: template argument 2 is invalid
src/Overview.hpp:22:10: error: ‘<expression error>’ in namespace ‘std’ does not name a type
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/main.cpp:5:
src/Globals.hpp:14:37: error: ‘Hyprutils’ has not been declared
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                     ^~~~~~~~~
src/Globals.hpp:14:83: error: expected unqualified-id before ‘,’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                                                                   ^
src/Globals.hpp:14:83: error: expected ‘)’ before ‘,’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                             ~                                                     ^
      |                                                                                   )
src/Globals.hpp:14:93: error: expected initializer before ‘*’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                                                                             ^
src/main.cpp:58:1: error: ‘Hyprutils’ does not name a type
   58 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pRenderHook;
      | ^~~~~~~~~
src/main.cpp:59:1: error: ‘Hyprutils’ does not name a type
   59 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pConfigReloadHook;
      | ^~~~~~~~~
src/main.cpp:60:1: error: ‘Hyprutils’ does not name a type
   60 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pOpenLayerHook;
      | ^~~~~~~~~
src/main.cpp:61:1: error: ‘Hyprutils’ does not name a type
   61 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pCloseLayerHook;
      | ^~~~~~~~~
src/main.cpp:62:1: error: ‘Hyprutils’ does not name a type
   62 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pMouseButtonHook;
      | ^~~~~~~~~
src/main.cpp:63:1: error: ‘Hyprutils’ does not name a type
   63 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pMouseAxisHook;
      | ^~~~~~~~~
src/main.cpp:64:1: error: ‘Hyprutils’ does not name a type
   64 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pTouchDownHook;
      | ^~~~~~~~~
src/main.cpp:65:1: error: ‘Hyprutils’ does not name a type
   65 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pTouchUpHook;
      | ^~~~~~~~~
src/main.cpp:66:1: error: ‘Hyprutils’ does not name a type
   66 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pSwipeBeginHook;
      | ^~~~~~~~~
src/main.cpp:67:1: error: ‘Hyprutils’ does not name a type
   67 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pSwipeUpdateHook;
      | ^~~~~~~~~
src/main.cpp:68:1: error: ‘Hyprutils’ does not name a type
   68 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pSwipeEndHook;
      | ^~~~~~~~~
src/main.cpp:69:1: error: ‘Hyprutils’ does not name a type
   69 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pKeyPressHook;
      | ^~~~~~~~~
src/main.cpp:70:1: error: ‘Hyprutils’ does not name a type
   70 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pSwitchWorkspaceHook;
      | ^~~~~~~~~
src/main.cpp:71:1: error: ‘Hyprutils’ does not name a type
   71 | Hyprutils::Memory::CSharedPointer<HOOK_CALLBACK_FN> g_pAddMonitorHook;
      | ^~~~~~~~~
src/main.cpp: In function ‘PLUGIN_DESCRIPTION_INFO pluginInit(void*)’:
src/main.cpp:460:5: error: ‘g_pConfigReloadHook’ was not declared in this scope
  460 |     g_pConfigReloadHook = HyprlandAPI::registerCallbackDynamic(pHandle, "configReloaded", [&] (void* thisptr, SCallbackInfo& info, std::any data) { reloadConfig(); });
      |     ^~~~~~~~~~~~~~~~~~~
src/main.cpp:467:5: error: ‘g_pRenderHook’ was not declared in this scope
  467 |     g_pRenderHook = HyprlandAPI::registerCallbackDynamic(pHandle, "render", onRender);
      |     ^~~~~~~~~~~~~
src/main.cpp:470:5: error: ‘g_pOpenLayerHook’ was not declared in this scope
  470 |     g_pOpenLayerHook = HyprlandAPI::registerCallbackDynamic(pHandle, "openLayer", [&] (void* thisptr, SCallbackInfo& info, std::any data) { g_layoutNeedsRefresh = true; });
      |     ^~~~~~~~~~~~~~~~
src/main.cpp:471:5: error: ‘g_pCloseLayerHook’ was not declared in this scope
  471 |     g_pCloseLayerHook = HyprlandAPI::registerCallbackDynamic(pHandle, "closeLayer", [&] (void* thisptr, SCallbackInfo& info, std::any data) { g_layoutNeedsRefresh = true; });
      |     ^~~~~~~~~~~~~~~~~
src/main.cpp:477:5: error: ‘g_pMouseButtonHook’ was not declared in this scope
  477 |     g_pMouseButtonHook = HyprlandAPI::registerCallbackDynamic(pHandle, "mouseButton", onMouseButton);
      |     ^~~~~~~~~~~~~~~~~~
src/main.cpp:478:5: error: ‘g_pMouseAxisHook’ was not declared in this scope
  478 |     g_pMouseAxisHook = HyprlandAPI::registerCallbackDynamic(pHandle, "mouseAxis", onMouseAxis);
      |     ^~~~~~~~~~~~~~~~
src/main.cpp:480:5: error: ‘g_pTouchDownHook’ was not declared in this scope
  480 |     g_pTouchDownHook = HyprlandAPI::registerCallbackDynamic(pHandle, "touchDown", onTouchDown);
      |     ^~~~~~~~~~~~~~~~
src/main.cpp:481:5: error: ‘g_pTouchUpHook’ was not declared in this scope
  481 |     g_pTouchUpHook = HyprlandAPI::registerCallbackDynamic(pHandle, "touchUp", onTouchUp);
      |     ^~~~~~~~~~~~~~
src/main.cpp:483:5: error: ‘g_pSwipeBeginHook’ was not declared in this scope
  483 |     g_pSwipeBeginHook = HyprlandAPI::registerCallbackDynamic(pHandle, "swipeBegin", onSwipeBegin);
      |     ^~~~~~~~~~~~~~~~~
src/main.cpp:484:5: error: ‘g_pSwipeUpdateHook’ was not declared in this scope
  484 |     g_pSwipeUpdateHook = HyprlandAPI::registerCallbackDynamic(pHandle, "swipeUpdate", onSwipeUpdate);
      |     ^~~~~~~~~~~~~~~~~~
src/main.cpp:485:5: error: ‘g_pSwipeEndHook’ was not declared in this scope
  485 |     g_pSwipeEndHook = HyprlandAPI::registerCallbackDynamic(pHandle, "swipeEnd", onSwipeEnd);
      |     ^~~~~~~~~~~~~~~
src/main.cpp:487:5: error: ‘g_pKeyPressHook’ was not declared in this scope
  487 |     g_pKeyPressHook = HyprlandAPI::registerCallbackDynamic(pHandle, "keyPress", onKeyPress);
      |     ^~~~~~~~~~~~~~~
src/main.cpp:489:5: error: ‘g_pSwitchWorkspaceHook’ was not declared in this scope
  489 |     g_pSwitchWorkspaceHook = HyprlandAPI::registerCallbackDynamic(pHandle, "workspace", onWorkspaceChange);
      |     ^~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:500:5: error: ‘g_pAddMonitorHook’ was not declared in this scope
  500 |     g_pAddMonitorHook = HyprlandAPI::registerCallbackDynamic(pHandle, "monitorAdded", [&] (void* thisptr, SCallbackInfo& info, std::any data) { registerMonitors(); });
      |     ^~~~~~~~~~~~~~~~~
In file included from src/Overview.cpp:1:
src/Overview.hpp:22:28: error: ‘Hyprutils’ was not declared in this scope
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                            ^~~~~~~~~
src/Overview.hpp:22:81: error: template argument 1 is invalid
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                                                                                 ^~
src/Overview.hpp:22:84: error: template argument 1 is invalid
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                                                                                    ^~~~~~~~~~~
src/Overview.hpp:22:84: error: template argument 2 is invalid
src/Overview.hpp:22:10: error: ‘<expression error>’ in namespace ‘std’ does not name a type
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/Overview.cpp:2:
src/Globals.hpp:14:37: error: ‘Hyprutils’ has not been declared
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                     ^~~~~~~~~
src/Globals.hpp:14:83: error: expected unqualified-id before ‘,’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                                                                   ^
src/Globals.hpp:14:83: error: expected ‘)’ before ‘,’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                             ~                                                     ^
      |                                                                                   )
src/Globals.hpp:14:93: error: expected initializer before ‘*’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                                                                             ^
src/Overview.cpp: In member function ‘void CHyprspaceWidget::show()’:
src/Overview.cpp:52:9: error: ‘oLayerAlpha’ was not declared in this scope
   52 |     if (oLayerAlpha.empty() && Config::hideRealLayers) {
      |         ^~~~~~~~~~~
src/Overview.cpp: In member function ‘void CHyprspaceWidget::hide()’:
src/Overview.cpp:87:40: error: ‘oLayerAlpha’ was not declared in this scope
   87 |             auto oAlpha = std::find_if(oLayerAlpha.begin(), oLayerAlpha.end(), [&] (const auto& tuple) {return std::get<0>(tuple) == ls;});
      |                                        ^~~~~~~~~~~
src/Overview.cpp:97:40: error: ‘oLayerAlpha’ was not declared in this scope
   97 |             auto oAlpha = std::find_if(oLayerAlpha.begin(), oLayerAlpha.end(), [&] (const auto& tuple) {return std::get<0>(tuple) == ls;});
      |                                        ^~~~~~~~~~~
src/Overview.cpp:105:5: error: ‘oLayerAlpha’ was not declared in this scope
  105 |     oLayerAlpha.clear();
      |     ^~~~~~~~~~~
In file included from src/Render.cpp:1:
src/Overview.hpp:22:28: error: ‘Hyprutils’ was not declared in this scope
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                            ^~~~~~~~~
src/Overview.hpp:22:81: error: template argument 1 is invalid
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                                                                                 ^~
src/Overview.hpp:22:84: error: template argument 1 is invalid
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |                                                                                    ^~~~~~~~~~~
src/Overview.hpp:22:84: error: template argument 2 is invalid
src/Overview.hpp:22:10: error: ‘<expression error>’ in namespace ‘std’ does not name a type
   22 |     std::vector<std::tuple<Hyprutils::Memory::CWeakPointer<CLayerSurface>, float>> oLayerAlpha;
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/Render.cpp:2:
src/Globals.hpp:14:37: error: ‘Hyprutils’ has not been declared
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                     ^~~~~~~~~
src/Globals.hpp:14:83: error: expected unqualified-id before ‘,’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                                                                   ^
src/Globals.hpp:14:83: error: expected ‘)’ before ‘,’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                             ~                                                     ^
      |                                                                                   )
src/Globals.hpp:14:93: error: expected initializer before ‘*’ token
   14 | typedef void (*tRenderLayer)(void*, Hyprutils::Memory::CWeakPointer<CLayerSurface>, CMonitor*, timespec*, bool);
      |                                                                                             ^
src/Render.cpp:53:6: error: variable or field ‘renderLayerStub’ declared void
   53 | void renderLayerStub(Hyprutils::Memory::CWeakPointer<CLayerSurface> pLayer, CMonitor* pMonitor, CBox rectOverride, timespec* time) {
      |      ^~~~~~~~~~~~~~~
src/Render.cpp:53:22: error: ‘Hyprutils’ has not been declared
   53 | void renderLayerStub(Hyprutils::Memory::CWeakPointer<CLayerSurface> pLayer, CMonitor* pMonitor, CBox rectOverride, timespec* time) {
      |                      ^~~~~~~~~
src/Render.cpp:53:67: error: expected primary-expression before ‘>’ token
   53 | void renderLayerStub(Hyprutils::Memory::CWeakPointer<CLayerSurface> pLayer, CMonitor* pMonitor, CBox rectOverride, timespec* time) {
      |                                                                   ^
src/Render.cpp:53:69: error: ‘pLayer’ was not declared in this scope
   53 | void renderLayerStub(Hyprutils::Memory::CWeakPointer<CLayerSurface> pLayer, CMonitor* pMonitor, CBox rectOverride, timespec* time) {
      |                                                                     ^~~~~~
src/Render.cpp:53:85: error: expected primary-expression before ‘*’ token
   53 | void renderLayerStub(Hyprutils::Memory::CWeakPointer<CLayerSurface> pLayer, CMonitor* pMonitor, CBox rectOverride, timespec* time) {
      |                                                                                     ^
src/Render.cpp:53:87: error: ‘pMonitor’ was not declared in this scope; did you mean ‘CMonitor’?
   53 | void renderLayerStub(Hyprutils::Memory::CWeakPointer<CLayerSurface> pLayer, CMonitor* pMonitor, CBox rectOverride, timespec* time) {
      |                                                                                       ^~~~~~~~
      |                                                                                       CMonitor
src/Render.cpp:53:102: error: expected primary-expression before ‘rectOverride’
   53 | void renderLayerStub(Hyprutils::Memory::CWeakPointer<CLayerSurface> pLayer, CMonitor* pMonitor, CBox rectOverride, timespec* time) {
      |                                                                                                      ^~~~~~~~~~~~
src/Render.cpp:53:124: error: expected primary-expression before ‘*’ token
   53 | void renderLayerStub(Hyprutils::Memory::CWeakPointer<CLayerSurface> pLayer, CMonitor* pMonitor, CBox rectOverride, timespec* time) {
      |                                                                                                                            ^
src/Render.cpp: In member function ‘void CHyprspaceWidget::draw()’:
src/Render.cpp:117:247: warning: narrowing conversion of ‘Config::panelBorderWidth’ from ‘int’ to ‘double’ [-Wnarrowing]
  117 |         CBox borderBox = {widgetBox.x, owner->vecPosition.y + (Config::onBottom * owner->vecTransformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset.value()* owner->scale) * bottomInvert, owner->vecTransformedSize.x, Config::panelBorderWidth};
      |                                                                                                                                                                                                                                               ~~~~~~~~^~~~~~~~~~~~~~~~
src/Render.cpp:215:17: error: ‘renderLayerStub’ was not declared in this scope; did you mean ‘tRenderLayer’?
  215 |                 renderLayerStub(ls, owner, layerBox, &time);
      |                 ^~~~~~~~~~~~~~~
      |                 tRenderLayer
src/Render.cpp:221:17: error: ‘renderLayerStub’ was not declared in this scope; did you mean ‘tRenderLayer’?
  221 |                 renderLayerStub(ls, owner, layerBox, &time);
      |                 ^~~~~~~~~~~~~~~
      |                 tRenderLayer
src/Render.cpp:289:21: error: ‘renderLayerStub’ was not declared in this scope; did you mean ‘tRenderLayer’?
  289 |                     renderLayerStub(ls, owner, layerBox, &time);
      |                     ^~~~~~~~~~~~~~~
      |                     tRenderLayer
src/Render.cpp:297:21: error: ‘renderLayerStub’ was not declared in this scope; did you mean ‘tRenderLayer’?
  297 |                     renderLayerStub(ls, owner, layerBox, &time);
      |                     ^~~~~~~~~~~~~~~
      |                     tRenderLayer
make: *** [Makefile:7: all] Error 1


✖ Plugin Hyprspace failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.
```

**Comment by James-Randall-14** [comment]
Fixed by [#62](https://github.com/KZDKM/Hyprspace/pull/62). Different error, but the fix was the same.
