### ISSUE TITLE
Failed to build on v0.41.2

### ISSUE THREAD

**Issue by shadowelite-sec** [KZDKM/Hyprspace#61]
```
✔ Hyprland headers OK                                                                    
 → Building Hyprspace                                                                    
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/shadow && PKG_CONFIG_PATH="/home/shadow/.local/share/hyprpm/headersRoot/share/pkgconfig" make all
g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++2b -O2 `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` src/Input.cpp src/Layout.cpp src/main.cpp src/Overview.cpp src/Render.cpp -o Hyprspace.so
src/Input.cpp: In member function ‘bool CHyprspaceWidget::axisEvent(double, Hyprutils::Math::Vector2D)’:
src/Input.cpp:92:24: error: ‘getWorkspaceIDFromString’ was not declared in this scope; did you mean ‘getWorkspaceIDNameFromString’?
   92 |             int wsID = getWorkspaceIDFromString("r-1", outName);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~
      |                        getWorkspaceIDNameFromString
src/Input.cpp:98:24: error: ‘getWorkspaceIDFromString’ was not declared in this scope; did you mean ‘getWorkspaceIDNameFromString’?
   98 |             int wsID = getWorkspaceIDFromString("r+1", outName);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~
      |                        getWorkspaceIDNameFromString
src/Render.cpp: In member function ‘void CHyprspaceWidget::draw()’:
src/Render.cpp:117:247: warning: narrowing conversion of ‘Config::panelBorderWidth’ from ‘int’ to ‘double’ [-Wnarrowing]
  117 |         CBox borderBox = {widgetBox.x, owner->vecPosition.y + (Config::onBottom * owner->vecTransformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset.value()* owner->scale) * bottomInvert, owner->vecTransformedSize.x, Config::panelBorderWidth};
      |                                                                                                                                                                                                                                               ~~~~~~~~^~~~~~~~~~~~~~~~
make: *** [Makefile:7: all] Error 1
```
