### ISSUE TITLE
Hyprspace fails to build with Hyprland v0.56.0 (AnimationManager.hpp missing)

### ISSUE THREAD

**Issue by Lothaireg** [KZDKM/Hyprspace#239]
Hi! Thanks for maintaining Hyprspace.

After upgrading to Hyprland v0.56.0 today, Hyprspace no longer builds through hyprpm.

I checked the currently open issues and pull requests but couldn't find anything related to compatibility with v0.56.0, so I'm opening this report in case nobody has encountered it yet.

Environment:

* Hyprland: v0.56.0
* Hyprland commit: 36b2e0cfe0c6094dbc47bd42a437431315bb3087
* Hyprspace: latest master
* Installation method: hyprpm

Steps to reproduce:

* Run: hyprpm update -v

Observed behavior:

The build fails during compilation with the following error:

src/Globals.hpp:15:10: fatal error:
hyprland/src/managers/animation/AnimationManager.hpp:
No such file or directory

This error is reported for several compilation units (Input.cpp, Layout.cpp, main.cpp, Overview.cpp, and Render.cpp).

hyprpm then reports:

"Hyprland's ABI changed and some repositories failed to update: no plugins will be loaded until every repository updates successfully."

Additionally, running "hyprctl plugins list" returns:

"no plugins loaded"

Expected behavior:

Hyprspace should build successfully against Hyprland v0.56.0 and be loadable through hyprpm.

Additional information:

It looks like AnimationManager.hpp may have been removed, renamed, or moved in Hyprland v0.56.0, causing Hyprspace to fail to compile against the latest headers.

Please let me know if additional logs would be helpful or if you'd like me to test a potential fix.

**Comment by ImanolBarba** [comment]
can you test this PR? https://github.com/KZDKM/Hyprspace/pull/238

**Comment by Lothaireg** [comment]
> can you test this PR? https://github.com/KZDKM/Hyprspace/pull/238

Hi, I’m currently away and won’t be able to test it until later this week. I’ll report back once I’ve had a chance to try it!

**Comment by Lothaireg** [comment]
> can you test this PR? [#238](https://github.com/KZDKM/Hyprspace/pull/238)

Hi! I finally had some time to test it.

Tested on Hyprland v0.56.1 (5c9377c15f85c50648f35ca5a213754f95b93ca0).

migrate-v2 builds successfully using make all.
Hyprspace.so loads correctly with hyprctl plugin load.
The plugin works as expected after adding the Lua binding (hl.bind("SUPER + TAB", ...)) to hyprland.lua.
The overview feature is functional and Hyprland remains stable during use.

I did notice a minor visual artifact: workspace previews seem to reflect the shifted workspace state while the overview is open, resulting in a slight recursive/mirror-like effect. This may be intentional, but I thought it was worth mentioning from a UX perspective.

This seems to resolve the original compilation issue on my side. I'll leave the issue open for you to decide whether to close it once the PR is merged.

Thanks for the work on the migration!

**Comment by ImanolBarba** [comment]
Many thanks for testing!

> I did notice a minor visual artifact: workspace previews seem to reflect the shifted workspace state while the overview is open, resulting in a slight recursive/mirror-like effect. This may be intentional, but I thought it was worth mentioning from a UX perspective.

Can you make a screenshot of it? Just want to compare before/after my changes and see if it's by design or I screwed something

**Comment by Lothaireg** [comment]
Hi again, sorry for the poor-quality picture. I cannot manage to get a proper screenshot so I took a picture with my phone.
As you can see we can observe the shift of the desktop environment when toggling Hyprspace. My best guess is that it should come from plugin:overview:affectStrut (as noted in the README file).

<img width="2532" height="1424" alt="Image" src="https://github.com/user-attachments/assets/90231c91-a159-4c89-a361-88c4b2b726be" />

**Comment by ImanolBarba** [comment]
Ah no worries, this is intended behaviour to obscure the overview panel itself, unrelated to the changes I made AFAIK

**Comment by ahoyarou** [comment]
yes
