### ISSUE TITLE
cannot build on hyprland 0.52.0

### ISSUE THREAD

**Issue by acup1** [KZDKM/Hyprspace#209]
```shell
error: builder for '/nix/store/v7kg5knalnm1kbfvx3w8fnah4fi113jv-Hyprspace-0.1+date=2025-09-28_e54884d.drv' failed with exit code 2;
       last 25 log lines:
       > src/main.cpp:291:68: error: 'class CCompositor' has no member named 'm_lastMonitor'
       >   291 |     targetMonitor = targetMonitor ? targetMonitor : g_pCompositor->m_lastMonitor.lock();
       >       |                                                                    ^~~~~~~~~~~~~
       > src/main.cpp: In function 'PLUGIN_DESCRIPTION_INFO pluginInit(void*)':
       > src/main.cpp:515:31: warning: 'bool HyprlandAPI::addDispatcher(void*, const std::string&, std::function<void(std::__cxx11::basic_string<char>)>)' is de
precated [-Wdeprecated-declarations]
       >   515 |     HyprlandAPI::addDispatcher(pHandle, "overview:toggle", ::dispatchToggleOverview);
       >       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > In file included from /nix/store/k9qkqf0x9cy1yxcw4xd7q75w28n3lajy-hyprland-0.52.0+date=2025-11-27_e42185b-dev/include/hyprland/src/plugins/PluginSystem
.hpp:5,
       >                  from src/main.cpp:1:
       > /nix/store/k9qkqf0x9cy1yxcw4xd7q75w28n3lajy-hyprland-0.52.0+date=2025-11-27_e42185b-dev/include/hyprland/src/plugins/PluginAPI.hpp:250:33: note: declar
ed here
       >   250 |     APICALL [[deprecated]] bool addDispatcher(HANDLE handle, const std::string& name, std::function<void(std::string)> handler);
       >       |                                 ^~~~~~~~~~~~~
       > src/main.cpp:516:31: warning: 'bool HyprlandAPI::addDispatcher(void*, const std::string&, std::function<void(std::__cxx11::basic_string<char>)>)' is de
precated [-Wdeprecated-declarations]
       >   516 |     HyprlandAPI::addDispatcher(pHandle, "overview:open", ::dispatchOpenOverview);
       >       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > /nix/store/k9qkqf0x9cy1yxcw4xd7q75w28n3lajy-hyprland-0.52.0+date=2025-11-27_e42185b-dev/include/hyprland/src/plugins/PluginAPI.hpp:250:33: note: declar
ed here
       >   250 |     APICALL [[deprecated]] bool addDispatcher(HANDLE handle, const std::string& name, std::function<void(std::string)> handler);
       >       |                                 ^~~~~~~~~~~~~
       > src/main.cpp:517:31: warning: 'bool HyprlandAPI::addDispatcher(void*, const std::string&, std::function<void(std::__cxx11::basic_string<char>)>)' is de
precated [-Wdeprecated-declarations]
       >   517 |     HyprlandAPI::addDispatcher(pHandle, "overview:close", ::dispatchCloseOverview);
       >       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > /nix/store/k9qkqf0x9cy1yxcw4xd7q75w28n3lajy-hyprland-0.52.0+date=2025-11-27_e42185b-dev/include/hyprland/src/plugins/PluginAPI.hpp:250:33: note: declar
ed here
       >   250 |     APICALL [[deprecated]] bool addDispatcher(HANDLE handle, const std::string& name, std::function<void(std::string)> handler);
       >       |                                 ^~~~~~~~~~~~~
       > make: *** [Makefile:7: all] Error 1
       For full logs, run:
         nix log /nix/store/v7kg5knalnm1kbfvx3w8fnah4fi113jv-Hyprspace-0.1+date=2025-09-28_e54884d.drv
error: 1 dependencies of derivation '/nix/store/6j2cxjfzdi68sijdazzrxf27yvc56l36-hm_hyprhyprland.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1si330izjdmin45snw5lmdlvl85swx5x-activation-script.drv' failed to build
error: 1 dependencies of derivation '/nix/store/61cp4r1s8p4qyb2nsk8sixjwy5b49r1d-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fvpz6kgc7ykzrc9qh4fm6aidb1bgkjsz-unit-home-manager-acup.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3jfzr86fcx1w9bmlrl4x4l4si4x0phwx-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/s11i2yjxa0fhziwk222mdswn2pgwcz7v-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/aijw1kjicm51gmap8klh2mjcdf6w9viq-nixos-system-nixos-25.11.20251002.7df7ff7.drv' failed to build
```

**Comment by k1ng440** [comment]
Doesn't work for me on 0.52.1
