### ISSUE TITLE
Fails to build on Hyperland 0.49.0

### ISSUE THREAD

**Issue by ATUK-OoD** [KZDKM/Hyprspace#182]
Hello. I found this project while transisioning from gnome. And I wanted give it a shot. As said I'm really new to hyperland, so I'm sorry if I'm missing something important.

My steps:
1. clone repo into Downloads dir
2. cd Hyprspace
3. make all
and this gives error:

```g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++2b -O2 `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` src/Input.cpp src/Layout.cpp src/main.cpp src/Overview.cpp src/Render.cpp -o Hyprspace.so
src/main.cpp: In function ‘PLUGIN_DESCRIPTION_INFO pluginInit(void*)’:
src/main.cpp:515:31: warning: ‘bool HyprlandAPI::addDispatcher(void*, const std::string&, std::function<void(std::__cxx11::basic_string<char>)>)’ is deprecated [-Wdeprecated-declarations]
  515 |     HyprlandAPI::addDispatcher(pHandle, "overview:toggle", ::dispatchToggleOverview);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/hyprland/src/plugins/PluginSystem.hpp:5,
                 from src/main.cpp:1:
/usr/include/hyprland/src/plugins/PluginAPI.hpp:249:33: note: declared here
  249 |     APICALL [[deprecated]] bool addDispatcher(HANDLE handle, const std::string& name, std::function<void(std::string)> handler);
      |                                 ^~~~~~~~~~~~~
src/main.cpp:516:31: warning: ‘bool HyprlandAPI::addDispatcher(void*, const std::string&, std::function<void(std::__cxx11::basic_string<char>)>)’ is deprecated [-Wdeprecated-declarations]
  516 |     HyprlandAPI::addDispatcher(pHandle, "overview:open", ::dispatchOpenOverview);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hyprland/src/plugins/PluginAPI.hpp:249:33: note: declared here
  249 |     APICALL [[deprecated]] bool addDispatcher(HANDLE handle, const std::string& name, std::function<void(std::string)> handler);
      |                                 ^~~~~~~~~~~~~
src/main.cpp:517:31: warning: ‘bool HyprlandAPI::addDispatcher(void*, const std::string&, std::function<void(std::__cxx11::basic_string<char>)>)’ is deprecated [-Wdeprecated-declarations]
  517 |     HyprlandAPI::addDispatcher(pHandle, "overview:close", ::dispatchCloseOverview);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hyprland/src/plugins/PluginAPI.hpp:249:33: note: declared here
  249 |     APICALL [[deprecated]] bool addDispatcher(HANDLE handle, const std::string& name, std::function<void(std::string)> handler);
      |                                 ^~~~~~~~~~~~~
src/Render.cpp: In function ‘void renderRect(Hyprutils::Math::CBox, CHyprColor)’:
src/Render.cpp:46:67: error: cannot convert ‘Hyprutils::Memory::CUniquePointer<CRectPassElement>’ to ‘Hyprutils::Memory::CSharedPointer<IPassElement>’
   46 |     g_pHyprRenderer->m_renderPass.add(makeUnique<CRectPassElement>(rectdata));
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
      |                                                                   |
      |                                                                   Hyprutils::Memory::CUniquePointer<CRectPassElement>
In file included from /usr/include/hyprland/src/render/OpenGL.hpp:22,
                 from /usr/include/hyprland/src/render/Renderer.hpp:7,
                 from src/Globals.hpp:5,
                 from src/Render.cpp:2:
/usr/include/hyprland/src/render/pass/Pass.hpp:14:34: note: initializing argument 1 of ‘void CRenderPass::add(Hyprutils::Memory::CSharedPointer<IPassElement>)’
   14 |     void    add(SP<IPassElement> elem);
      |                                  ^
src/Render.cpp: In function ‘void renderRectWithBlur(Hyprutils::Math::CBox, CHyprColor)’:
src/Render.cpp:54:67: error: cannot convert ‘Hyprutils::Memory::CUniquePointer<CRectPassElement>’ to ‘Hyprutils::Memory::CSharedPointer<IPassElement>’
   54 |     g_pHyprRenderer->m_renderPass.add(makeUnique<CRectPassElement>(rectdata));
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
      |                                                                   |
      |                                                                   Hyprutils::Memory::CUniquePointer<CRectPassElement>
/usr/include/hyprland/src/render/pass/Pass.hpp:14:34: note: initializing argument 1 of ‘void CRenderPass::add(Hyprutils::Memory::CSharedPointer<IPassElement>)’
   14 |     void    add(SP<IPassElement> elem);
      |                                  ^
src/Render.cpp: In function ‘void renderBorder(Hyprutils::Math::CBox, CGradientValueData, int)’:
src/Render.cpp:64:69: error: cannot convert ‘Hyprutils::Memory::CUniquePointer<CBorderPassElement>’ to ‘Hyprutils::Memory::CSharedPointer<IPassElement>’
   64 |     g_pHyprRenderer->m_renderPass.add(makeUnique<CBorderPassElement>(data));
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
      |                                                                     |
      |                                                                     Hyprutils::Memory::CUniquePointer<CBorderPassElement>
/usr/include/hyprland/src/render/pass/Pass.hpp:14:34: note: initializing argument 1 of ‘void CRenderPass::add(Hyprutils::Memory::CSharedPointer<IPassElement>)’
   14 |     void    add(SP<IPassElement> elem);
      |                                  ^
src/Render.cpp: In function ‘void renderWindowStub(PHLWINDOW, PHLMONITOR, PHLWORKSPACE, Hyprutils::Math::CBox, timespec*)’:
src/Render.cpp:99:76: error: cannot convert ‘Hyprutils::Memory::CUniquePointer<CRendererHintsPassElement>’ to ‘Hyprutils::Memory::CSharedPointer<IPassElement>’
   99 |     g_pHyprRenderer->m_renderPass.add(makeUnique<CRendererHintsPassElement>(CRendererHintsPassElement::SData{renderModif}));
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                            |
      |                                                                            Hyprutils::Memory::CUniquePointer<CRendererHintsPassElement>
/usr/include/hyprland/src/render/pass/Pass.hpp:14:34: note: initializing argument 1 of ‘void CRenderPass::add(Hyprutils::Memory::CSharedPointer<IPassElement>)’
   14 |     void    add(SP<IPassElement> elem);
      |                                  ^
src/Render.cpp: In lambda function:
src/Render.cpp:102:80: error: cannot convert ‘Hyprutils::Memory::CUniquePointer<CRendererHintsPassElement>’ to ‘Hyprutils::Memory::CSharedPointer<IPassElement>’
  102 |         g_pHyprRenderer->m_renderPass.add(makeUnique<CRendererHintsPassElement>(CRendererHintsPassElement::SData{SRenderModifData{}}));
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                |
      |                                                                                Hyprutils::Memory::CUniquePointer<CRendererHintsPassElement>
/usr/include/hyprland/src/render/pass/Pass.hpp:14:34: note: initializing argument 1 of ‘void CRenderPass::add(Hyprutils::Memory::CSharedPointer<IPassElement>)’
   14 |     void    add(SP<IPassElement> elem);
      |                                  ^
src/Render.cpp: In function ‘void renderWindowStub(PHLWINDOW, PHLMONITOR, PHLWORKSPACE, Hyprutils::Math::CBox, timespec*)’:
src/Render.cpp:80:16: warning: unused variable ‘oRenderModifEnable’ [-Wunused-variable]
   80 |     const auto oRenderModifEnable = g_pHyprOpenGL->m_renderData.renderModif.enabled;
      |                ^~~~~~~~~~~~~~~~~~
src/Render.cpp: In function ‘void renderLayerStub(PHLLS, PHLMONITOR, Hyprutils::Math::CBox, timespec*)’:
src/Render.cpp:141:76: error: cannot convert ‘Hyprutils::Memory::CUniquePointer<CRendererHintsPassElement>’ to ‘Hyprutils::Memory::CSharedPointer<IPassElement>’
  141 |     g_pHyprRenderer->m_renderPass.add(makeUnique<CRendererHintsPassElement>(CRendererHintsPassElement::SData{renderModif}));
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                            |
      |                                                                            Hyprutils::Memory::CUniquePointer<CRendererHintsPassElement>
/usr/include/hyprland/src/render/pass/Pass.hpp:14:34: note: initializing argument 1 of ‘void CRenderPass::add(Hyprutils::Memory::CSharedPointer<IPassElement>)’
   14 |     void    add(SP<IPassElement> elem);
      |                                  ^
src/Render.cpp: In lambda function:
src/Render.cpp:144:80: error: cannot convert ‘Hyprutils::Memory::CUniquePointer<CRendererHintsPassElement>’ to ‘Hyprutils::Memory::CSharedPointer<IPassElement>’
  144 |         g_pHyprRenderer->m_renderPass.add(makeUnique<CRendererHintsPassElement>(CRendererHintsPassElement::SData{SRenderModifData{}}));
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                |
      |                                                                                Hyprutils::Memory::CUniquePointer<CRendererHintsPassElement>
/usr/include/hyprland/src/render/pass/Pass.hpp:14:34: note: initializing argument 1 of ‘void CRenderPass::add(Hyprutils::Memory::CSharedPointer<IPassElement>)’
   14 |     void    add(SP<IPassElement> elem);
      |                                  ^
src/Render.cpp: In function ‘void renderLayerStub(PHLLS, PHLMONITOR, Hyprutils::Math::CBox, timespec*)’:
src/Render.cpp:128:16: warning: unused variable ‘oRenderModifEnable’ [-Wunused-variable]
  128 |     const auto oRenderModifEnable = g_pHyprOpenGL->m_renderData.renderModif.enabled;
      |                ^~~~~~~~~~~~~~~~~~
src/Render.cpp: In member function ‘void CHyprspaceWidget::draw()’:
src/Render.cpp:191:248: warning: narrowing conversion of ‘Config::panelBorderWidth’ from ‘int’ to ‘double’ [-Wnarrowing]
  191 | nsformedSize.y) + (Config::panelHeight + Config::reservedArea - curYOffset->value() * owner->m_scale) * bottomInvert, owner->m_transformedSize.x, Config::panelBorderWidth};
      |                                                                                                                                                   ~~~~~~~~^~~~~~~~~~~~~~~~
src/Render.cpp:207:69: error: cannot convert ‘Hyprutils::Memory::CUniquePointer<CFakeDamageElement>’ to ‘Hyprutils::Memory::CSharedPointer<IPassElement>’
  207 |     g_pHyprRenderer->m_renderPass.add(makeUnique<CFakeDamageElement>(fakeDamage));
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
      |                                                                     |
      |                                                                     Hyprutils::Memory::CUniquePointer<CFakeDamageElement>
/usr/include/hyprland/src/render/pass/Pass.hpp:14:34: note: initializing argument 1 of ‘void CRenderPass::add(Hyprutils::Memory::CSharedPointer<IPassElement>)’
   14 |     void    add(SP<IPassElement> elem);
      |                                  ^
make: *** [Makefile:7: all] Error 1```

Hyprland 0.49.0
Arch 6.15.5

This really looks like a great project. And any help would be greatly appreciated.

**Comment by sstu** [comment]
+1

**Comment by myamusashi** [comment]
Only works in 0.50.0

**Comment by ATUK-OoD** [comment]
Ok, updating to 0.50.0 resolved the issue.
Thanks for help!
Marking this issue as solved.
